name: Docker Image CI

on:
  push:
    branches:
      - "!main"
  pull_request:
    branches: [main]

env:
  ORGANIZATION: "smerrell"
  IMAGE_NAME: "terraform-python-build"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Lint Dockerfile
        uses: brpaz/hadolint-action@master
        with:
          dockerfile: "Dockerfile"

  build:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag $ORGANIZATION/$IMAGE_NAME:$(date +%s)
